### ISSUE TITLE
Why this tool has two entries and randomly shows usages data on visualizer? 

### ISSUE THREAD

**Issue by jitendravyas** [patrickhulce/third-party-web#152]
https://github.com/patrickhulce/third-party-web/blob/master/data/entities.js#L1400

https://github.com/patrickhulce/third-party-web/blob/master/data/entities.js#L9940

Also, see this recorded video of the visualizer page. Sometimes usages data are shown 0 and sometimes 4724 and sometimes not when I search for it

https://monosnap.com/file/BQgR8QDpLC1PfhnZS6CvBjYi5gWmAg

**Comment by patrickhulce** [comment]
> Why this tool has two entries 

It's a bug! PR to fix it welcome :)

> Also, see this recorded video of the visualizer page. 

Not sure, I'll have to look into it.

**Comment by christobill** [comment]
@jitendravyas @patrickhulce 

This was fixed by this PR:
https://github.com/patrickhulce/third-party-web/pull/161

The reason of this bug is there were 2 entities for vwo:
- https://github.com/patrickhulce/third-party-web/pull/161/files#diff-847abf984e44d2b08939cb61782a12405f37b5ecf1c6ed9deca81d354070c8caL1400
- https://github.com/patrickhulce/third-party-web/pull/161/files#diff-847abf984e44d2b08939cb61782a12405f37b5ecf1c6ed9deca81d354070c8caL9939

**Comment by patrickhulce** [comment]
Thanks @christobill! 👍
