### ISSUE TITLE
Kameleoon missing in the analytic table

### ISSUE THREAD

**Issue by jdoujet** [patrickhulce/third-party-web#226]
Hi,

We noticed that Kameleoon details are missing from the analytics table. We can't see Kameleoon's performance anymore. Could you add it back in the README, please?

Could it be due to the following failed action: https://github.com/patrickhulce/third-party-web/actions/runs/10025071622

Let me know.

Thanks.

**Comment by patrickhulce** [comment]
Thanks very much for filing @jdoujet ! This is somewhat intentional. 

Kameleoon dropped below the [1000 unique domains threshold](https://github.com/patrickhulce/third-party-web/blob/82f19004382b7b41b2cb41d8a81cb982a6ffe622/data/2024-06-01-entity-scripting.json#L2860) required to appear on the README. This could either be due to organic usage reductions, changes in HTTPArchive dataset, or from increased usage of dynamic domains (see #225).

Either way, we don't perform changes to manually add in specific third-party companies because they dipped below the popularity limit, so I'll be closing this issue, but please do feel free to chime in with the believed reason if you learn more.

**Comment by jdoujet** [comment]
Hi Patrick,

Thanks a lot for your response and explanation.

It makes sense.

Thanks,

Le mer. 7 août 2024 à 23:15, Patrick Hulce ***@***.***> a
écrit :
