### ISSUE TITLE
Joomla! ??¿¿

### ISSUE THREAD

**Issue by Boumy** [patrickhulce/third-party-web#4]
Hi. Thank very much for this huge work. Is it possible that you omitted Joomla! ?
![images](https://user-images.githubusercontent.com/13934889/54000036-312c1700-4146-11e9-98ee-3f1465cb4eef.png)

**Comment by patrickhulce** [comment]
@Boumy does Joomla also offer hosting as a service? I was under the impression most Joomla users self-host/go through a shared hosting provider, but I could certainly be wrong :)

While investigating library/platform usage would be an awesome direction to go as well, this project currently focuses on third party *origins*, so if Joomla resources aren't being served by a common origin among Joomla users, then it likely won't be surfaced here.

**Comment by Boumy** [comment]
Hi.
Sorry for the delay. I have had a doubt and, more over, I couldn't find a link that certifies that Joomla is on its way to propose hosting. Today I have found it. Here it is: 
https://launch.joomla.org/

**Comment by patrickhulce** [comment]
Thanks @Boumy! That just seems like they've partnered with someone (CloudAccess) to offer you hosting though. It's a not a shared third-party server like `cdn.wordpress.com` or something that serves assets to the end user and so isn't really trackable from the client side.

I'm going to go ahead and close this issue since it seems like there's not a primary third party origin we can track, but feel free to open a PR if you end up finding one! :)
