### ISSUE TITLE
www.google.se/ads/ga-audiences ?

### ISSUE THREAD

**Issue by soulgalore** [patrickhulce/third-party-web#70]
Hi @patrickhulce I started to going through top 100 Swedish websites and categorising missing 3rd parties.

One of the most used ones that is missed right now is _www.google.se/ads/ga-audiences_ - for me I would categorise that URL/domain as ads but it's the main Google domain in Sweden. Maybe you have some insights? :)

Best
Peter

**Comment by patrickhulce** [comment]
Thanks for filing Peter! :) 

So far folks have been adding the `www.google.<country code>` to the `Other Google APIs/SDKs` entity but the concern about multiple categories served over the same domain is a tricky one to solve. It's mostly a Google-specific problem because most companies don't span several categories anyhow, but the only way I could think to solve it would be adding support for a URL pattern :/

Maybe we can dig up some HTTPArchive stats on these domains and see if the primary third-party inclusion pattern is for the ad requests and just move them over?

**Comment by soulgalore** [comment]
It's ok for me to just categorise them as Google for now, then I can re-categorise them in other libs :)

**Comment by patrickhulce** [comment]
We're going to improve some things in this area with #112 👍
